#!/usr/bin/env node
/**
 * A-Gent Marketing Agent
 * 
 * Manages: social media, blog content, website updates, email campaigns
 * Reports to: Sales Agent (parent)
 * Escalations to: Mark (human)
 * 
 * Run: node marketing-agent.js [command]
 * 
 * Commands:
 *   daily        - Run daily marketing routine
 *   social       - Queue today's social posts from calendar
 *   blog         - Work on blog drafts
 *   report       - Generate weekly marketing report
 *   help         - Show this help
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Load capabilities
const social = require('./capabilities/social');
const contentCalendar = require('./capabilities/content_calendar');
const blog = require('./capabilities/blog');

// ─── Config ───────────────────────────────────────────────

const AGENT_NAME = 'Marketing Agent';
const AGENT_VERSION = '1.0.0';
const LOG_DIR = path.join(__dirname, 'memory', 'daily');
const MEMORY_FILE = path.join(__dirname, 'memory', 'MEMORY.md');

// ─── Logging ──────────────────────────────────────────────

function log(message, level = 'INFO') {
  const timestamp = new Date().toISOString();
  const logLine = `[${timestamp}] [${level}] ${message}`;
  console.log(logLine);
  
  // Also write to today's log file
  const today = new Date().toISOString().split('T')[0];
  const logFile = path.join(LOG_DIR, `${today}.md`);
  
  if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
  fs.appendFileSync(logFile, logLine + '\n');
}

// ─── Social Media ──────────────────────────────────────────

async function runSocialMedia() {
  log('Starting social media routine...');
  
  try {
    // Get unqueued posts from calendar
    const posts = contentCalendar.getUnqueuedPosts();
    
    if (posts.length === 0) {
      log('No posts to queue today');
      return { queued: 0 };
    }
    
    log(`Found ${posts.length} posts to queue`);
    
    const results = [];
    for (const post of posts) {
      try {
        const channels = post.channel === 'linkedin' 
          ? ['a_gent_linkedin'] 
          : post.channel === 'both'
            ? ['a_gent_x', 'a_gent_linkedin']
            : ['a_gent_x'];
        
        for (const channel of channels) {
          const result = await social.queuePost(post.text, channel);
          log(`Queued to ${channel}: ${post.text.slice(0, 50)}...`);
        }
        
        contentCalendar.markQueued(post.text);
        results.push({ text: post.text, status: 'queued' });
        
      } catch (err) {
        log(`Failed to queue post: ${err.message}`, 'ERROR');
        results.push({ text: post.text, status: 'failed', error: err.message });
      }
    }
    
    return { queued: results.filter(r => r.status === 'queued').length, failed: results.filter(r => r.status === 'failed').length };
    
  } catch (err) {
    log(`Social media routine failed: ${err.message}`, 'ERROR');
    return { error: err.message };
  }
}

// ─── Blog ──────────────────────────────────────────────────

async function runBlogWork() {
  log('Checking blog drafts...');
  
  try {
    const drafts = blog.listDrafts('draft');
    const reviews = blog.listDrafts('review');
    
    log(`Drafts: ${drafts.length} | In review: ${reviews.length}`);
    
    if (drafts.length > 0) {
      log('Drafts ready for review:', 'INFO');
      for (const draft of drafts) {
        log(`  - ${draft.title} (${draft.filename})`, 'INFO');
      }
    }
    
    return { drafts: drafts.length, reviews: reviews.length };
    
  } catch (err) {
    log(`Blog work failed: ${err.message}`, 'ERROR');
    return { error: err.message };
  }
}

// ─── Weekly Report ─────────────────────────────────────────

async function generateWeeklyReport() {
  log('Generating weekly marketing report...');
  
  // Get this week's queued posts
  const posts = contentCalendar.getThisWeeksPosts();
  const queuedPosts = posts.filter(p => p.text.includes('[QUEUED]'));
  
  const report = `
📊 Marketing Weekly Report — Week of ${new Date().toISOString().split('T')[0]}

## Posts
- Planned: ${posts.length}
- Queued: ${queuedPosts.length}
- Remaining: ${posts.length - queuedPosts.length}

## Blog
- Drafts in pipeline: ${blog.listDrafts('draft').length}
- Awaiting review: ${blog.listDrafts('review').length}
- Published: ${blog.listDrafts('published').length}

## Status
${queuedPosts.length >= posts.length / 2 ? '✅ On track' : '⚠️ Behind schedule'}

## Flags
- None (or list specific issues requiring attention)

---
Generated by ${AGENT_NAME} v${AGENT_VERSION}
`;
  
  log(report);
  return report;
}

// ─── Daily Routine ─────────────────────────────────────────

async function runDailyRoutine() {
  log(`Starting daily routine for ${AGENT_NAME}`);
  
  const results = {
    social: await runSocialMedia(),
    blog: await runBlogWork(),
    timestamp: new Date().toISOString(),
  };
  
  log(`Daily routine complete. Social: ${results.social.queued || 0} queued, Blog: ${results.blog.drafts || 0} drafts`);
  
  return results;
}

// ─── Main ──────────────────────────────────────────────────

const command = process.argv[2] || 'help';

const commands = {
  daily: runDailyRoutine,
  social: () => runSocialMedia(),
  blog: () => runBlogWork(),
  report: () => generateWeeklyReport(),
  help: () => {
    console.log(`
${AGENT_NAME} v${AGENT_VERSION}
=====================

Usage: node marketing-agent.js [command]

Commands:
  daily        Run daily marketing routine (social + blog)
  social       Queue today's social posts from calendar
  blog         Check and work on blog drafts
  report       Generate weekly marketing report
  help         Show this help

Reports to: Sales Agent (parent)
Escalates to: Mark (human)
`);
    return { done: true };
  },
};

if (!commands[command]) {
  console.log(`Unknown command: ${command}`);
  commands.help();
  process.exit(1);
}

commands[command]()
  .then(result => {
    if (result && result.done) return; // help command returns plain object
    if (result && result.error) {
      console.error('Error:', result.error);
      process.exit(1);
    }
  })
  .catch(err => {
    console.error('Fatal error:', err.message);
    process.exit(1);
  });